site_name: ui
site_description: Shared UI components with theming for use across HOTOSM tools.
# strict: true
site_url: "https://www.hotosm.org"

repo_name: "hotosm/ui"
repo_url: "https://github.com/hotosm/ui/"
edit_uri: "edit/main/docs/"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/hotosm/"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/hotosm"
    - icon: "fontawesome/solid/globe"
      link: "https://www.hotosm.org"
  copyright: Copyright &copy; 2010 HOTOSM
  generator: false

theme:
  name: material
  palette:
    primary: custom
  favicon: images/favicon.png
  logo: images/hot_logo.png
  # custom_dir: docs/overrides

extra_javascript:
  - https://s3.amazonaws.com/hotosm-ui/latest/ui.js

extra_css:
  - css/extra.css
  - https://s3.amazonaws.com/hotosm-ui/latest/style.css

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.emoji:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - mdx_truly_sane_lists

plugins:
  - search
  - exclude:
      glob:
        - plugins/*
        - node_modules/*

nav:
  - Home: index.md
  - About: about.md
  - Components:
      - Button: components/hot-button.md
  - Usage: usage.md
  - Storybook: storybook.md
  - License: LICENSE.md
  - Changelog: CHANGELOG.md
