name: 📖 Publish Docs

on:
  push:
    paths:
      - docs/**
      - src/**
      - mkdocs.yml
    branches: [main]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  # build_stories:
  #   uses: hotosm/gh-workflows/.github/workflows/stories_build.yml@1.2.1
  #   with:
  #     npm_cmd: build:stories
  #     output_path: docs/stories

  publish_docs:
    uses: hotosm/gh-workflows/.github/workflows/mkdocs_build.yml@1.2.1
    needs: [build_doxygen]
    with:
      image: ghcr.io/${{ github.repository }}:ci
      # stories: true
