name: 📖 Publish Docs

on:
  push:
    paths:
      - docs/**
      - components/**
      - mkdocs.yml
    branches: [main]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  build_stories:
    uses: hotosm/gh-workflows/.github/workflows/stories_build.yml@1.4.6
    with:
      command: build:docs
      output_path: docs/stories

  publish_docs:
    uses: hotosm/gh-workflows/.github/workflows/mkdocs_build.yml@1.4.6
    needs: [build_stories]
    with:
      stories: true
