name: 🚩 Publish to npmjs.org

on:
  release:
    types: [published]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Publish to npmjs.org
        uses: ./npm_publish.yml@1.0.0
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
